### ISSUE TITLE
Training curves and time to train

### ISSUE THREAD

**Issue by zubair-irshad** [DaLi-Jack/SSR-code#10]
Great work! Do you plan on releasing the tensorboard or wandb training curves. This would help reproduce the training performance  (for instance final PSNR achieved etc). Also do you happen to have an estimate of the time it took to complete training on your end with the setup specified in your paper? 

Thanks in advance for your help and greatly appreciate the code release!

**Comment by DaLi-Jack** [comment]
Hi! Thanks for your interest in our work!
Our training curve is at the link below:
[training curve](https://drive.google.com/file/d/1xZuZQ7ELMu-JBeFkdnL0HjLDNgHOBqRY/view?usp=drive_link)
On Front3D, we trained for about 3 days, and on Pix3D, it was about 1.5 days.

**Comment by zubair-irshad** [comment]
Thanks so much, this answers my questions!
