### ISSUE TITLE
推理无结果

### ISSUE THREAD

**Issue by EMP138** [DaLi-Jack/SSR-code#11]
<img width="333" alt="{607E63B0-D208-4493-AEFB-11F2FBE76F5A}" src="https://github.com/DaLi-Jack/SSR-code/assets/134022780/a81a8777-ba1f-4e11-b60d-282a98aaf7eb">
<img width="269" alt="{F4D23247-B1F3-4841-9668-543B5152FD91}" src="https://github.com/DaLi-Jack/SSR-code/assets/134022780/699b77c4-1fc4-4128-8e3e-6ae6441c3e52">
对demo和sunrgbd进行推理后，demo未推理，sunrgbd推理完成却没显示任何结果，也能没有保存文件，这是为什么

**Comment by DaLi-Jack** [comment]
Hi! You can check if there is output in `./output/front3d_ckpt/out/bed/769_5`, if you have not changed the default saving path. 
By the way, this information can be found in [inference_sunrgbd.py](https://github.com/DaLi-Jack/SSR-code/blob/534337e6894218ca920c14d4db2648fe136ccdc4/inference_sunrgbd.py#L25)
