### ISSUE TITLE
Train model on custom dataset

### ISSUE THREAD

**Issue by vineet22h** [DaLi-Jack/SSR-code#12]
I want to train the model on custom dataset, which includes image, mask and mesh. so need to create all necessary files like gt-sdf, depth map, normal map, camera parameters, etc. Can u provide any reference code or git repo?

**Comment by DaLi-Jack** [comment]
Hi. I'm sorry that my data processing code is raw and I don't plan to make it public. However, I will provide you with the data processing code I referenced at the time, which I hope will be useful to you:
1.SDF generation tool: [kaolin](https://kaolin.readthedocs.io/en/latest/)
2.BlenderProc rendering tool: [blenderproc](https://github.com/DLR-RM/BlenderProc)

**Comment by DaLi-Jack** [comment]
Additionally, I believe this issue #8 might be helpful to you.
