### ISSUE TITLE
Dataset and Checkpoint file were not found

### ISSUE THREAD

**Issue by dhsoon02** [DaLi-Jack/SSR-code#13]
Dear Author,
Thank you for your interesting research proposal.

I am very happy that the code for this study has been released. 
However, I would like to ask you about the drive link to the dataset and checkpoint file, as it seems to be incorrect.

I look forward to your reply.

**Comment by dhsoon02** [comment]
I'm getting Error 404 on google drive

**Comment by DaLi-Jack** [comment]
Hi! Thanks for your interest in our work!
We apologize for the inconvenience caused by the invalid Google Drive link. We have re-uploaded the data and checkpoints and updated the link. Everything should work fine now. Thank you for bringing this to our attention!
