### ISSUE TITLE
Inference on Single Image

### ISSUE THREAD

**Issue by joeyism** [DaLi-Jack/SSR-code#4]
Hi guys, this is great work. I was wondering if how I can run inference just on a single image, as a test on how well the model generates. For example, if I provide just an image of the couch (as seem in the demo), what do I need to execute to be able to generate the mesh?

**Comment by DaLi-Jack** [comment]
Hi! This is a good question.
In our method, mesh recovery from a single image is divided into two stages, the first stage is single-image 3D object detection, and another stage is 3D object reconstruction which relies on the object detection results. We follow InstPIFu to use the Im3D detector as the single-image 3D object detector, for more details please refer to #2. This repo only releases the 3D object reconstruction codes, so if you want to infer on a single image, please refer to [InstPIFu Object Detetion](https://github.com/GAP-LAB-CUHK-SZ/InstPIFu/tree/main#object-detection) to get the 3D object detection results, and then use SUNRGBD code `inference_sunrgbd.py` for the 3D object reconstruction.
