### ISSUE TITLE
Get mesh_color.ply with no color in inference

### ISSUE THREAD

**Issue by XuM007** [DaLi-Jack/SSR-code#6]
Hi, thank you so much for your wonderful work. But the colored mesh I got from the inference seems to have no color.

 Specifically, I followed setup, data, and checkpoints in the repo. Then ran `python inference.py --config configs/train_pix3d.yaml` in the Export mesh with texture section. After running successfully, I was able to get the folder of each imgid_255, which contained mesh_color.ply and mesh_none_color.ply, but I found that mesh_color.ply did not have the results I expected. This was what I expected.
![image](https://github.com/DaLi-Jack/SSR-code/assets/101008794/29566d32-1015-4caa-a07c-7549dab20fc1)

But in fact I checked it with blender and got this mesh whose view shading mode was rendering.
 
![image](https://github.com/DaLi-Jack/SSR-code/assets/101008794/8e0fbb31-5715-4b8e-b6d8-49e06a7cfe90)

A specific example, the mesh_color.ply corresponding to 0384_255 in the chair is 6933KB, and the mesh_none_color.ply is 6278KB. What may be the reason for not getting colored mesh? Looking forward to your reply.

**Comment by DaLi-Jack** [comment]
Hi! This is a problem with Blender’s display of .ply colors. You can follow these steps to display the color of .ply in Blender.
**Step 1: add new material for the mesh**
![1](https://github.com/DaLi-Jack/SSR-code/assets/70205757/893dbc3c-0882-46a6-9069-743ee2c003c6)

**Step 2: add color attribute**
<div align="center">
  <img src="https://github.com/DaLi-Jack/SSR-code/assets/70205757/f8e9cfec-db92-4634-90f4-7fad1f683849" alt="Image 1" width="400"/>
</div>
<div align="center">
  <img src="https://github.com/DaLi-Jack/SSR-code/assets/70205757/a9620e8b-be9f-4f5a-845e-0dab55a00dda" alt="Image 1" width="400"/>
</div>

**Step 3: use shading mode**
<div align="center">
  <img src="https://github.com/DaLi-Jack/SSR-code/assets/70205757/631e80ab-5e32-4d77-8bda-a4e4544a66c3" alt="Image 1" width="400"/>
</div>

**The result:**

![5](https://github.com/DaLi-Jack/SSR-code/assets/70205757/94ed3a14-c3f1-4511-ae52-29c1afa47a1d)


Besides, you can use **MeshLab** to check the color of .ply, which is more convenient.
![image](https://github.com/DaLi-Jack/SSR-code/assets/70205757/b8d04629-be8e-4c0f-82c8-5be8d08eb2ab)

**Comment by XuM007** [comment]
Thank you for your timely reply. My problem has been solved.
