### ISSUE TITLE
Large-Scale Images 

### ISSUE THREAD

**Issue by alpakbaci** [DaLi-Jack/SSR-code#9]
I am working on a study on large scale 3D reconstruction and conducting a literature review for my paper. My question is, have you had the opportunity to test your project successfully with outdoor images, which have been successfully tested with indoor images? Is it possible to revise this study according to outdoor environments?

Thank you for your fantastic project.

**Comment by DaLi-Jack** [comment]
Hi! Thanks for your interest in our work!
In this paper, we mainly focus on indoor scenes and have not tried on large-scale outdoor scenes. The main limitations may come from the dataset (Front3D and Pix3D are both indoor datasets) and the ray-sampling method (not applicable in unbounded scenes). But I think the method in this paper should also be applicable to outdoor scene reconstruction.
Hope my answer can help you!
